[ulister]
noloadtypes=1999
nopreviewtypes=1999
keepinmemory=1

; optionsdir=%COMMANDER_PATH%\Plugins\wlx\ulister
; CODE PAGE 1251 TEST:
; optionsdir=c:\тест кириллица

; Ctrl-Shift-F1 просмотр эскизов
; Qtrl-Q быстрый просмотр
; F3 просмотр

; invert mouse wheel horizontal scroll
mwhscrollinvert=on

[clipboard]
; This options controls the clipboard formats that the viewer attempts to place on the clipboard
; skip|on|off

ascii=on
rtf=on

; turn it on!
unicode=on

bitmap=on
windib=on
metafile=on
palette=on

dragdrop=on

; controls the format the spreadsheet or the database data takes when copied to the clipboard
; RTF: in clipboard formats that support it, the spreadsheet selection will be copied as a table
; skip|rtf|tabs|optimizedtabs
spreadsheet=rtf
database=rtf

[viewer]
; Display engine
; skip|draft|normal|preview|weblayout
wpdisplaymode=normal
htmldisplaymode=weblayout
emaildisplaymode=normal

; skip|draft|normal|normalhidden
spreadsheetdisplaymode=normal

; Extended for preview or weblayout mode of previous options.
; These settings are applied correctly only from the second launch of ulister after
; changes in the .ini file due to an bug in the Outside In Viewer library (workaround):
; skip|original|width|window
webprevwpfitmode=width
webprevhtmlfitmode=width
webprevemailfitmode=width

; For bitmap and vector graphics
; skip|best|original|window|height|width|stretch|imagesize
vectorfitmode=window
bitmapfitmode=window
