[ulister]
noloadtypes=1999
nopreviewtypes=1999
keepinmemory=1

; optionsdir=%COMMANDER_PATH%\Plugins\wlx\ulister
; CODE PAGE 1251 TEST:
; optionsdir=c:\тест кириллица

; Ctrl-Shift-F1 просмотр эскизов
; Qtrl-Q быстрый просмотр
; F3 просмотр
